spring:
  application:
    name: ms-inventory
  datasource:
    url: "jdbc:mysql://localhost:3306/db_inventory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    username: root
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
  flyway:
    enabled: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    discovery:
      enabled: false

server:
  port: 9005

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

logging:
  level:
    root: ERROR
    cl.duoc.ms_inventory: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    enabled: false

feign:
  url:
    ms-vehicles: http://localhost:9004

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: "jdbc:mysql://mysql-db:3306/db_inventory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

server:
  port: ${PORT:9005}

feign:
  url:
    ms-vehicles: http://ms-vehicles:9004
