spring.application.name=ms-test-drive
server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/db_test_drive?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.output.ansi.enabled=always

spring.flyway.enabled=true

logging.level.root=ERROR
logging.level.cl.duoc.ms_test_drive=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


feign.url.ms-clients=http://localhost:8081
feign.url.ms-vehicles=http://localhost:8084

spring.cloud.discovery.enabled=false
eureka.client.enabled=false