spring.application.name=ms-auth
server.port=9011

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

spring.datasource.url=jdbc:mysql://localhost:3306/db_auth?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.output.ansi.enabled=always

spring.flyway.enabled=true

logging.level.root=ERROR
logging.level.cl.duoc.ms_auth=DEBUG

spring.cloud.discovery.enabled=false
eureka.client.enabled=false

jwt.secret=DSY1103-Automotora-SecretKeyForJWT-HS256-2026-Auth
jwt.expiration-ms=3600000
